#+TITLE: Mathematical Components: Research Papers
#+OPTIONS: toc:1
#+OPTIONS: ^:nil
#+OPTIONS: html-postamble:nil
#+OPTIONS: num:nil
#+HTML_HEAD: <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
#+HTML_HEAD: <style type="text/css"> body {font-family: Arial, Helvetica; margin-left: 5em; font-size: large;} </style>
#+HTML_HEAD: <style type="text/css"> h1 {margin-left: 0em; padding: 0px; text-align: center} </style>
#+HTML_HEAD: <style type="text/css"> h2 {margin-left: 0em; padding: 0px; color: #580909} </style>
#+HTML_HEAD: <style type="text/css"> h3 {margin-left: 1em; padding: 0px; color: #C05001;} </style>
#+HTML_HEAD: <style type="text/css"> body { width: 1100px; margin-left: 30px; }</style>

This is a list of research papers and theses using the Mathematical
Components libraries and published (among others) in the following
venues:
- ITP = Interactive Theorem Proving
- CPP = Certified Programs and Proofs
- CICM = Conference on Intelligent Computer Mathematics
- LMCS = Logical Methods in Computer Science
- ICFP = International Conference on Functional Programming
- POPL = Principles of Programming Languages
- PPDP = Principles and Practice of Declarative Programming

This list is non-exhaustive.  Initial contents come from the [[https://github.com/math-comp/math-comp/wiki/Publications][official
wiki]].

Your paper or thesis is not in the list? Send [[mailto:mathcomp-dev@inria.fr?subject=MathComp related paper][us]] a message to correct this.

* Mathematics

- Florent Bréhard, Assia Mahboubi and Damien Pous. _A certificate-based
  approach to formally verified approximations_. ITP 2019. [[https://hal-cstb.archives-ouvertes.fr/LAAS-MAC/hal-02088529v1][pdf]]
- Daniel E. Severín.
  _Formalization of the Domination Chain with Weighted Parameters_. ITP 2019. [[http://drops.dagstuhl.de/opus/volltexte/2019/11091/pdf/LIPIcs-ITP-2019-36.pdf][pdf]]
- Christian Doczkal, Damien Pous.
  _Graph Theory in Coq: Minors, Treewidth, and Isomorphisms_. Coq Workshop 2019. [[https://staff.aist.go.jp/reynald.affeldt/coq2019/coqws2019-doczkal-pous.pdf][pdf]]
- Reynald Affeldt, Cyril Cohen, Damien Rouhling.
  _Formalization techniques for asymptotic reasoning in classical analysis_.
  Journal of Formalized Reasoning. [[https://jfr.unibo.it/article/view/8124/8407][pdf]]
- Reynald Affeldt, Cyril Cohen, Assia Mahboubi, Damien Rouhling, Pierre-Yves Strub.
  _Classical Analysis with Coq_. Coq Workshop 2018. [[https://staff.aist.go.jp/reynald.affeldt/documents/coqws-reals.pdf][pdf]]
- Christian Doczkal, Guillaume Combette, Damien Pous.
  _A Formal Proof of the Minor-Exclusion Property for Treewidth-Two Graphs_. ITP 2018
- Xavier Allamigeon, Ricardo D. Katz.
  _A formalization of convex polyhedra based on the simplex method_. ITP 2017
- Evmorfia-Iro Bartzia.
  _A Formalization of Elliptic Curves for Cryptography_.
  PhD thesis, Université Paris-Saclay, 2017. [[https://pastel.archives-ouvertes.fr/tel-01563979/][pdf]]
- Guillaume Cano, Cyril Cohen, Maxime Dénès, Anders Mörtberg, Vincent Siles.
  _Formalized linear algebra over Elementary Divisor Rings in Coq_.
  LMCS 12(2), 2016
- Cyril Cohen, Boris Djalal.
  _Formalization of a newton series representation of polynomials_. CPP 2016
- Ken'ichi Kuga, Manabu Hagiwara, Mitsuharu Yamamoto.
  _Formalization of Bing's Shrinking Method in Geometric Topology_. CICM 2016
- Gallego Arias, Emilio Jesús, Pierre Jouvelot.
  _Adventures in the (not so) Complex Space_. Coq Workshop 2015. [[https://github.com/ejgallego/mini-dft-coq][paper, code, slides]]
- Frédéric Chyzak, Assia Mahboubi, Thomas Sibut-Pinote, Enrico Tassi.
  _A Computer-Algebra-Based Formal Proof of the Irrationality of ζ(3)_. ITP 2014
- Cyril Cohen, Anders Mörtberg.
  _A Coq Formalization of Finitely Presented Modules_. ITP 2014
- Anders Mörtberg.
  _Formalizing Refinements and Constructive Algebra in Type Theory_.
  PhD, University of Gothenburg, 2014
- Evmorfia-Iro Bartzia, Pierre-Yves Strub.
   _A Formal Library for Elliptic Curves in the Coq Proof Assistant_. ITP 2014
- Jónathan Heras, Thierry Coquand, Anders Mörtberg, Vincent Siles.
  _Computing persistent homology within Coq/SSReflect_. ACM Trans. Comput. Log. 14(4), 2013
- Georges Gonthier, Andrea Asperti, Jeremy Avigad, Yves Bertot, Cyril
  Cohen, François Garillot, Stéphane Le Roux, Assia Mahboubi, Russell
  O'Connor, Sidi Ould Biha, Ioana Pasca, Laurence Rideau, Alexey
  Solovyev, Enrico Tassi, Laurent Théry.
  _A Machine-Checked Proof of the Odd Order Theorem_. ITP 2013
- Maxime Dénès, Anders Mörtberg, Vincent Siles.
  _A Refinement-Based Approach to Computational Algebra in Coq_. ITP 2012
- Jónathan Heras, Maxime Dénès, Gadea Mata, Anders Mörtberg, María Poza, Vincent Siles.
  _Towards a Certified Computation of Homology Groups for Digital Images_.
  4th International Workshop on Computational Topology in Image Context, 2012
- Assia Mahboubi, Cyril Cohen.
  _Formal proofs in real algebraic geometry: from ordered fields to quantifier elimination_.
  LMCS 8(1), 2012.
- Thierry Coquand, Anders Mörtberg, Vincent Siles.
  _Coherent and Strongly Discrete Rings in Type Theory_. CPP 2012
- Cyril Cohen.
  _Formalized algebraic numbers: construction and first-order theory_.
  PhD thesis, Ecole Polytechnique, 2011 
- Jónathan Heras, María Poza, Maxime Dénès, Laurence Rideau.
  _Incidence Simplicial Matrices Formalized in Coq/SSReflect_. Calculemus/MKM 2011: 30-44
- Georges Gonthier.
   _Point-Free, Set-Free Concrete Linear Algebra_. ITP 2011

** Robotics

- Cyril Cohen, Damien Rouhling.
  _A Formal Proof in Coq of LaSalle's Invariance Principle_. ITP 2017
- Reynald Affeldt, Cyril Cohen.
  _Formal Foundations of 3D Geometry to Model Robot Manipulators_. CPP 2017

* Programming and Algorithms

- Reynald Affeldt, David Nowak, Takafumi Saikawa.
  _A Hierarchy of Monadic Effects for Program Verification Using Equational Reasoning_.
  Mathematics of Program Construction (MPC 2019)
- Ran Chen, Cyril Cohen, Jean-Jacques Levy, Stephan Merz, Laurent Thery.
  _Formal Proof of Tarjan’s Strongly Connected Components Algorithm in Why3, Coq, and Isabelle_.
  ITP 2019
- Reynald Affeldt, Jacques Garrigue, Xuanrui Qi, Kazunari Tanaka.
  _Proving tree algorithms for succinct data structures_.
  ITP 2019, [[https://arxiv.org/pdf/1904.02809.pdf][pdf]]
- Reynald Affeldt, Jacques Garrigue, Xuanrui Qi, Kazunari Tanaka.
  _Experience Report: Type-Driven Development of Certified Tree Algorithms in Coq_.
  Coq Workshop 2019. [[https://staff.aist.go.jp/reynald.affeldt/coq2019/coqws2019-affeldt-garrigue-qi-tanaka.pdf][pdf]]
- Joseph Tassarotti, Robert Harper.
  Verified Tail Bounds for Randomized Programs. ITP 2018
- Cyril Cohen, Damien Rouhling.
  _A refinement-based approach to large scale reflection for algebra_. JFLA 2017
- Timmy Weerwag.
  _Verifying an elliptic curve cryptographic algorithm_using Coq and the Ssreflect extension_.
  Master’s thesis, Mathematics, Radboud University, 2016
- Beta Ziliani, Derek Dreyer, Neelakantan R. Krishnaswami, Aleksandar Nanevski, Viktor Vafeiadis.
  _Mtac: A Monad for Typed Tactic Programming in Coq_. Journal of Functional Programming, 2015
- Cyril Cohen, Maxime Dénès, Anders Mörtberg.
  _Refinements for free!_. CPP 2013
- Germán Andrés Delbianco, Aleksandar Nanevski.
  _Hoare-Style Reasoning with (Algebraic) Continuations_. ICFP 2013
- Andrew Kennedy, Nick Benton, Jonas B. Jensen, Pierre-Evariste Dagand.
  _Coq: the world's best macro assembler?_. PPDP 2013
- Beta Ziliani, Derek Dreyer, Neelakantan R. Krishnaswami, Aleksandar Nanevski, Viktor Vafeiadis.
  _Mtac: A Monad for Typed Tactic Programming in Coq_. ICFP 2013
- Aleksandar Nanevski, Viktor Vafeiadis, Josh Berdine.
   _Structuring the Verification of Heap-Manipulating Programs_. POPL 2010

** Concurrency

- Ilya Sergey, James R. Wilcox, Zachary Tatlock.
   _Programming and Proving with Distributed Protocols_. POPL 2018
- Germán Andrés Delbianco, Ilya Sergey, Aleksandar Nanevski, Anindya Banerjee.
  _Concurrent Data Structures Linked in Time_. ECOOP 2017
- Mitsuharu Yamamoto, Shogo Sekine, Saki Matsumoto.
  _Formalization of Karp-Miller Tree Construction on Petri Nets_. CPP 2017
- Germán Andrés Delbianco.
  _Hoare-style Reasoning with Higher-order Control: Continuations and Concurrency_.
  PhD thesis, Computer Science, Universidad Politécnica de Madrid, 2017
- Ilya Sergey, Aleksandar Nanevski, Anindya Banerjee, Germán Andrés Delbianco.
   _Hoare-style Specifications as Correctness Conditions for Non-linearizable Concurrent Objects_.
  OOPSLA 2016
- Ilya Sergey, Aleksandar Nanevski, Anindya Banerje.
   _Mechanized Verification of Fine-grained Concurrent Programs_. PLDI 2015 
- Ilya Sergey, Aleksandar Nanevski, Anindya Banerjee.
   _Specifying and Verifying Concurrent Algorithms with Histories and Subjectivity_. ESOP 2015
- Aleksandar Nanevski, Ruy Ley-Wild, Ilya Sergey, Germán Andrés Delbianco.
   _Communicating State Transition Systems for Fine-Grained Concurrent Resources_.
  ESOP 2014
- Ruy Ley-Wild, Aleksandar Nanevski.
   _Subjective Auxiliary State for Coarse-Grained Concurrency_. POPL 2013 

** Information Flow

- Aleksandar Nanevski, Anindya Banerjee, Deepak Garg.
  _Dependent Type Theory for Verification of Information Flow and Access Control Policies_.
  ACM Transactions on Programming Languages and Systems, 35(2):6:1-6:41, 2013
- Gordon Stewart, Anindya Banerjee, Aleksandar Nanevski.
  _Dependent Types for Enforcement of Information Flow and Erasure Policies in Heterogeneous Data Structures_.
  PPDP 2013.
- Aleksandar Nanevski, Anindya Banerjee, Deepak Garg.
   _Verification of Information Flow and Access Control Policies with Dependent Types_.
  2011 IEEE Symposium on Security and Privacy. [[https://ieeexplore.ieee.org/document/5958028][IEEE Xplore]]

* Other Applications

- George Pîrlea, Ilya Sergey. _Mechanising Blockchain Consensus_. CPP 2018
- Gallego Arias, Emilio Jesús, Olivier Hermant, Pierre Jouvelot.
  _A Taste of Sound Reasoning in Faust_.
  Linux Audio Conference 2015. [[https://github.com/ejgallego/mini-faust-coq][paper, code, slides]]
- Maxime Dénès, Benjamin Lesage, Yves Bertot, Adrien Richard.
 _Formal proof of theorems on genetic regulatory networks_.
  11th International Symposium on Symbolic and Numeric Algorithms for Scientific Computing (SYNACS 2009).
  [[https://ieeexplore.ieee.org/document/5460865][IEEE Xplore]]

** Logic, Types, and Verification

- Véronique Benzaken, Evelyne Contejean, Stefania Dumbrava.
  _Certifying Standard and Stratified Datalog Inference Engines in SSReflect_. ITP 2017
- F. Cerqueira, F. Stutz, B. Brandenburg.
   _Prosa: A Case for Readable Mechanized Schedulability Analysis_.
  28th Euromicro Conference on Real-Time Systems (ECRTS 2016). [[https://ieeexplore.ieee.org/document/7557887][IEEE Xplore]]
- Christian Doczkal, Gert Smolka.
  _Completeness and Decidability Results for CTL in Coq_. ITP 2014
- Christian Doczkal, Gert Smolka.
  _Constructive Completeness for Modal Logic with Transitive Closure_. CPP 2012
- Christian Doczkal, Gert Smolka.
  _Constructive Formalization of Hybrid Logic with Eventualities_. CPP 2011
- Kasper Svendsen, Lars Birkedal, Aleksandar Nanevski.
   _Partiality, State and Dependent Types_.
  International Conference on Typed Lambda Calculi and Applications (TLCA 2011). [[https://software.imdea.org/~aleks/papers/ihtt/ihtt-adm.pdf][pdf]]
 
** Information Theory

- Kyosuke Nakano, Manabu Hagiwara.
  _Formalization of binary symmetric erasure channel based on infotheo_.
  International Symposium on Information Theory and its Application 2016 (ISITA 2016)
- Reynald Affeldt, Jacques Garrigue, Takafumi Saikawa.
  _Formalization of Reed-Solomon codes and progress report on formalization of LDPC codes_.
  International Symposium on Information Theory and its Application 2016 (ISITA 2016)
- Reynald Affeldt, Jacques Garrigue.
  _Formalization of error-correcting codes: from Hamming to modern coding theory_. ITP 2015.
- Ryosuke Obi, Manabu Hagiwara, Reynald Affeldt.
   _Formalization of the variable-length source coding theorem: Direct part_.
  International Symposium on Information Theory and its Application 2014 (ISITA 2014)
- Reynald Affeldt, Manabu Hagiwara, Jonas Sénizergues.
  _Formalization of Shannon's theorems_. Journal of Automated Reasoning, 2014
- Reynald Affeldt, Manabu Hagiwara.
  _Formalization of Shannon's Theorems in SSReflect-Coq_. ITP 2012

* Tooling about SSReflect and Mathematical Components

- Erik Martin-Dorel, Enrico Tassi. _SSReflect in Coq 8.10_. Coq Workshop 2019. [[https://staff.aist.go.jp/reynald.affeldt/coq2019/coqws2019-martindorel-tassi.pdf][pdf]]
- Kazuhiko Sakaguchi. _Validating Mathematical Structures_. Coq Workshop 2019. [[https://staff.aist.go.jp/reynald.affeldt/coq2019/coqws2019-sakaguchi.pdf][pdf]]
- Jónathan Heras, Ekaterina Komendantskaya.
  _Proof Pattern Search in Coq/SSReflect_. [[https://arxiv.org/pdf/1402.0081.pdf][CoRR abs/1402.0081]] 2014
- Jónathan Heras, Ekaterina Komendantskaya.
   _Recycling Proof Patterns in Coq: Case Studies_. [[https://arxiv.org/pdf/1301.6039v4.pdf][CoRR abs/1301.6039]] 2014
- Georges Gonthier, Beta Ziliani, Aleksandar Nanevski, Derek Dreyer.
  _How to make ad hoc proof automation less ad hoc_. Journal of Functional Programming, 2013. [[https://people.mpi-sws.org/~beta/lessadhoc/lessadhoc-extended.pdf][pdf]]
- Vladimir Komendantsky, Alexander Konovalov, Steve Linton.
  _Interfacing Coq + SSReflect with GAP_. Electr. Notes Theor. Comput. Sci. 285
- Iain Whiteside, David Aspinall, Gudmund Grov.
  _An Essence of SSReflect_. CICM 2012
- Georges Gonthier, Enrico Tassi.
  _A Language of Patterns for Subterm Selection_. ITP 2012
- Georges Gonthier, Assia Mahboubi.
  _An introduction to small scale reflection in Coq_. Journal of Formalized Reasoning. [[https://hal.inria.fr/inria-00515548v4/document][pdf]]
- François Garillot, Georges Gonthier, Assia Mahboubi, Laurence Rideau.
  _Packaging Mathematical Structures_. TPHOLs 2009


